steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        printf '%s' "$$GITHUB_PAT" | docker login ghcr.io -u nlttin --password-stdin
        docker build \
          -t ghcr.io/nlttin/singpost-app-tracking:$SHORT_SHA \
          -t ghcr.io/nlttin/singpost-app-tracking:latest \
          .
        docker push ghcr.io/nlttin/singpost-app-tracking:$SHORT_SHA
        docker push ghcr.io/nlttin/singpost-app-tracking:latest
    secretEnv:
      - GITHUB_PAT

availableSecrets:
  secretManager:
    - versionName: projects/project-a8a37a94-04a7-44bf-a2c/secrets/github-pat/versions/latest
      env: GITHUB_PAT

options:
  logging: CLOUD_LOGGING_ONLY
