steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/sp-logistic-dev-app/singpost-app-tracking:$SHORT_SHA
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/sp-logistic-dev-app/singpost-app-tracking:latest
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - --all-tags
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/sp-logistic-dev-app/singpost-app-tracking

options:
  logging: CLOUD_LOGGING_ONLY
